version: '3.1'

services:

  mongo:
    image: mongo:2.4
    restart: always
    ports:
      - "27017-27019:27017-27019"
      - "28017:28017"
    environment:
      MONGO_INITDB_DATABASE: twxplorer
