project_name: twxplorer
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
python_version: "3.7.7"
python: /home/apps/sites/twxplorer/.venv/bin/python
service_port: "{{ twxplorer_port }}"

playbooks:
  - playbook.deploy-repo.yml
  - playbook.deploy-web.yml
  - playbook.restart.yml

init_env:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DB_ENGINE__DEFAULT: "mongo"
  DB_NAME__DEFAULT: "{{ project_name }}"
  DB_HOST__DEFAULT: "{{ env }}-mongo1.knilab.com"
  DB_PORT__DEFAULT: "27017"
  FLASK_SETTINGS_MODULE: "core.settings"
  FLASK_SETTINGS_FILE: "core/settings.py"
  FLASK_SECRET_KEY: "{{ vault_flask_secret_key }}"
  TWITTER_CONSUMER_KEY: "{{ vault_twitter_consumer_key }}"
  TWITTER_CONSUMER_SECRET: "{{ vault_twitter_consumer_secret }}"
  BITLY_USERNAME: "{{ vault_bitly_username }}"
  BITLY_APIKEY: "{{ vault_bitly_apikey }}"
  BITLY_DOMAIN: "{{ vault_bitly_domain }}"
  STATIC_URL: "/"


install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
virtualenv: "{{ deploy_dir }}/.venv"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
wsgi_application: "core.wsgi:application"
static_root: "{{ application_dir }}/static"
