project_name: twxplorer
gitdeploy_version: "1.0.1"

port: 9006
python: python2
type: flask

# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DB_ENGINE__DEFAULT: "mongo"
  DB_NAME__DEFAULT: "{{ project_name }}"
  DB_HOST__DEFAULT: "{{ env }}-mongo1.knilab.com"
  DB_PORT__DEFAULT: "27017"
  FLASK_SETTINGS_MODULE: "core.settings"
  FLASK_SETTINGS_FILE: "core/settings.py"
  FLASK_SECRET_KEY: "{{ vault_flask_secret_key }}"
  TWITTER_CONSUMER_KEY: "{{ vault_twitter_consumer_key }}"
  TWITTER_CONSUMER_SECRET: "{{ vault_twitter_consumer_secret }}"
  BITLY_USERNAME: "{{ vault_bitly_username }}"
  BITLY_APIKEY: "{{ vault_bitly_apikey }}"
  BITLY_DOMAIN: "{{ vault_bitly_domain }}"

static_dir: "{{ deploy_dir }}/static"
application_dir: "{{ deploy_dir }}"

# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
env_setup_script: "{{ deploy_dir }}/env.sh"
env_run_script: "{{ deploy_dir }}/env_run.sh"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "core.wsgi:application"
service_name: "apps/{{ project_name }}" # application services are now kept
                                        # in /etc/init/apps


# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env

# environment keys must match deployment branch names. Value is the name
# of the branch to be merged into this environment during deployment.
supported_envs:
  stg: master
  prd: stg
